baseURL = 'https://Axu991.github.io/'
languageCode = 'en-us'
title = 'Huang Xu | Homepage'
theme = 'PaperMod'

canonifyURLs = true
relativeURLs = false

[params]
  theme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  disableFingerprinting = true

  [params.profileMode]
    enabled = true
    title = "Huang Xu"
    subtitle = "水下机器人 | 仿生机器鱼 | 嵌入式开发"
    imageUrl = "" # 这里可以放你的头像链接，放在 static/ 目录下

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    name = "Log"
    url = "/logs/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
