baseURL = 'https://axu991.github.io/'
languageCode = 'en-us'
title = 'Xu Huang | Homepage'
theme = 'PaperMod'

relativeURLs = false
publishDir = "docs"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  

  [params.profileMode]
    enabled = true
    title = "Learn And Live"
    subtitle = "仿生机器鱼 | 嵌入式开发"
    imageUrl = "" # 这里可以放你的头像链接，放在 static/ 目录下

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 3

  [[menu.main]]
    name = "Updates"
    url = "/updates/"
    weight = 4



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
